// Validates the real, committed docs/site_data/failure_patterns.json and
// repair_candidates.json files against their TypeScript shapes -- these two
// files are manually curated (see docs/site_data/README.md's convention for
// graveyard.json), not generated by a Python export step, so there is no
// Python-side test covering their schema. This is that coverage.
import failurePatterns from "../../docs/site_data/failure_patterns.json";
import repairCandidates from "../../docs/site_data/repair_candidates.json";
import type { FailurePattern, FailurePatternEntry, RepairCandidate } from "@/lib/types";

const VALID_FAILURE_PATTERNS: FailurePattern[] = [
  "regime-filter-only",
  "grid-shift-artifact",
  "edge-over-random-negative",
  "sample-too-thin",
  "data-blocked",
  "mechanism-doesn't-transfer",
];

const VALID_REPAIR_STATUSES: RepairCandidate["status"][] = ["candidate", "testing", "watchlist", "promoted"];

describe("docs/site_data/failure_patterns.json", () => {
  const entries = failurePatterns as FailurePatternEntry[];

  it("is a non-empty array", () => {
    expect(Array.isArray(entries)).toBe(true);
    expect(entries.length).toBeGreaterThan(0);
  });

  it("has a unique name per entry (family is an intentional many-to-one grouping label, not a key)", () => {
    // `family` groups related named entries under a shared failure story on
    // purpose -- e.g. 6 distinct Range Mean Reversion experiments, 5 Macro
    // Regime asset-class extensions -- so family names legitimately repeat.
    // `name` is the real unique identifier (used to look up a specific entry
    // elsewhere, e.g. the LIQUIDATION_PREDICTOR test below).
    const names = entries.map((e) => e.name);
    expect(new Set(names).size).toBe(names.length);
  });

  it.each(entries.map((e) => [e.family, e] as const))("%s has a complete, well-typed entry", (_family, entry) => {
    expect(typeof entry.name).toBe("string");
    expect(entry.name.length).toBeGreaterThan(0);
    expect(typeof entry.family).toBe("string");
    expect(entry.family.length).toBeGreaterThan(0);
    expect(VALID_FAILURE_PATTERNS).toContain(entry.failure_pattern);
    expect(typeof entry.fixable).toBe("boolean");
    expect(typeof entry.source_doc).toBe("string");
    // A real docs/*.md path (hand-curated entries), OR the honest "no
    // written report" sentinel graveyard_distillation.py's own
    // _no_report_source_doc computes for LLM-drafted entries (which are
    // synthesized straight from aggregate DiedRecord stats, never from a
    // written report -- a fabricated .md path would be dishonest, so the
    // schema accepts this alternative instead of forcing one).
    expect(entry.source_doc).toMatch(/^(docs\/.+\.md|no written report --.+)$/);
  });

  it("gives every fixable entry a non-empty fix_rationale", () => {
    for (const entry of entries.filter((e) => e.fixable)) {
      expect(typeof entry.fix_rationale).toBe("string");
      expect((entry.fix_rationale ?? "").length).toBeGreaterThan(0);
    }
  });

  it("never attaches a fix_rationale to a non-fixable entry", () => {
    for (const entry of entries.filter((e) => !e.fixable)) {
      expect(entry.fix_rationale).toBeUndefined();
    }
  });

  it("tags LIQUIDATION_PREDICTOR (data-blocked) as not fixable, per the task's own example", () => {
    const entry = entries.find((e) => e.name === "LIQUIDATION_PREDICTOR");
    expect(entry?.failure_pattern).toBe("data-blocked");
    expect(entry?.fixable).toBe(false);
  });

  it("tags the Vol-Clustering multiplier as not fixable, per the task's own example", () => {
    const entry = entries.find((e) => e.family === "Position Sizing");
    expect(entry?.fixable).toBe(false);
  });
});

describe("docs/site_data/repair_candidates.json", () => {
  const candidates = repairCandidates as RepairCandidate[];

  it("registers at most 3 candidates", () => {
    expect(candidates.length).toBeGreaterThan(0);
    expect(candidates.length).toBeLessThanOrEqual(3);
  });

  it("has a unique hypothesis_name per candidate", () => {
    const names = candidates.map((c) => c.hypothesis_name);
    expect(new Set(names).size).toBe(names.length);
  });

  it.each(candidates.map((c) => [c.hypothesis_name, c] as const))(
    "%s has a complete, well-typed entry",
    (_name, candidate) => {
      expect(typeof candidate.parent_strategy).toBe("string");
      expect(candidate.parent_strategy.length).toBeGreaterThan(0);
      expect(VALID_FAILURE_PATTERNS).toContain(candidate.failure_pattern);
      expect(typeof candidate.diagnosis).toBe("string");
      expect(candidate.diagnosis.length).toBeGreaterThan(0);
      expect(typeof candidate.proposed_fix).toBe("string");
      expect(candidate.proposed_fix.length).toBeGreaterThan(0);
      expect(typeof candidate.hypothesis_name).toBe("string");
      expect(VALID_REPAIR_STATUSES).toContain(candidate.status);
    }
  );

  it("registers every candidate as 'candidate' status -- not backtested yet, per the task's own instruction", () => {
    expect(candidates.every((c) => c.status === "candidate")).toBe(true);
  });

  it("only proposes hypotheses for families failure_patterns.json marks fixable", () => {
    const fixableFamilies = new Set(
      (failurePatterns as FailurePatternEntry[]).filter((e) => e.fixable).map((e) => e.name)
    );
    for (const candidate of candidates) {
      expect(fixableFamilies.has(candidate.parent_strategy)).toBe(true);
    }
  });

  it("includes the RANGE_MEAN_REVERSION hypothesis, matching the hardcoded /lab lineage worked example", () => {
    expect(candidates.some((c) => c.parent_strategy === "RANGE_MEAN_REVERSION")).toBe(true);
  });
});
