// Mirrors the shapes nero_core/execution/export_site_data.py writes to
// docs/site_data/*.json, and the two manually-curated files
// (docs/site_data/site_summary.json, docs/site_data/graveyard.json).

export type SignalType = "ENTRY" | "EXIT" | "WATCH" | "NO_TRADE";

export interface LedgerRow {
  timestamp: string;
  strategy: string;
  strategy_version: string;
  asset: string;
  signal_type: SignalType;
  entry_price: number | null;
  exit_price: number | null;
  reasoning: string;
  candle_timestamp: string;
}

export interface LedgerExport {
  schema_version: number;
  last_updated: string;
  rows: LedgerRow[];
}

// nero_core.execution.backtest_evaluation -- structured backtest evidence,
// distinct from verification_status's free-text summary above. verdict_is/
// verdict_oos are null both when a config hasn't been evaluated with this
// structured format yet (see `note`) AND when it structurally cannot run
// through the standard classify_verdict harness (see `untestable_reason`)
// -- these are different claims, never conflated: read is_trades/oos_trades/
// is_expectancy_r/oos_expectancy_r alongside `untestable_reason` before
// assuming null means "no evidence."
export interface BacktestEvaluation {
  verdict_is: string | null;
  verdict_oos: string | null;
  is_trades: number | null;
  oos_trades: number | null;
  is_expectancy_r: number | null;
  oos_expectancy_r: number | null;
  evaluated_at: string | null;
  data_source: string | null;
  method: string | null;
  untestable_reason: string | null;
  note: string | null;
  // Badge-provenance work: distinguishes "wrong harness, but a real dedicated
  // backtest engine produced real evidence" (e.g. COINTEGRATION_PAIRS, false)
  // from "no historical data source will ever exist for this strategy" (e.g.
  // ORDERFLOW_IMBALANCE, NEWS_SENTIMENT, true) -- see lib/provenance.ts.
  // Optional because older cached exports predate this field; treat a
  // missing value as false (not permanently unbacktestable), never as true.
  permanently_unbacktestable?: boolean;
}

// Mirrors nero_core.execution.backtest_evaluation.DEFAULT_BACKTEST_EVALUATION
// exactly. Real, load-bearing fallback -- 2026-08-03 production incident: the
// live site's currently-fetched strategies.json (last regenerated by the cloud
// scheduler BEFORE this field existed at all) has NO backtest_evaluation key
// on any of its 37 entries, not just a missing sub-field -- entry.backtest_
// evaluation itself was `undefined`, crashing every page that read it
// (StrategyCard, the strategy detail page, provenance.ts) with a 500. Every
// consumer must read `entry.backtest_evaluation ?? DEFAULT_BACKTEST_EVALUATION`,
// never `entry.backtest_evaluation` directly -- the field is optional on
// StrategyRosterEntry below for exactly this reason, matching this file's own
// established convention for every other field added after the export schema
// was first written.
export const DEFAULT_BACKTEST_EVALUATION: BacktestEvaluation = {
  verdict_is: null,
  verdict_oos: null,
  is_trades: null,
  oos_trades: null,
  is_expectancy_r: null,
  oos_expectancy_r: null,
  evaluated_at: null,
  data_source: null,
  method: null,
  untestable_reason: null,
  note: "Not yet evaluated with this structured format — see the research status and linked source report above for the original backtest description.",
  permanently_unbacktestable: false,
};

export interface StrategyRosterEntry {
  name: string;
  version: string;
  asset: string;
  timeframe: string;
  verification_status: string;
  source_report: string | null;
  // Optional -- see DEFAULT_BACKTEST_EVALUATION's own comment. A currently-
  // fetched export can genuinely lack this key entirely if it predates the
  // field being added to the export schema; every consumer must fall back to
  // DEFAULT_BACKTEST_EVALUATION, never assume this is always present.
  backtest_evaluation?: BacktestEvaluation;
  // Badge-provenance work: the real first-commit date of the doc at
  // source_report (git-derived, hand-recorded -- see
  // nero_core.execution.source_reports.SOURCE_REPORT_WRITTEN_AT), null when
  // source_report itself is null or its date hasn't been recorded yet.
  // Optional because older cached exports predate this field.
  source_report_written_at?: string | null;
}

// Manually-curated docs/site_data/strategy_descriptions.json -- keyed by strategy_id
// (the family name, e.g. "PEAD"), one entry per family, not per individual
// config/version/asset. verification_note is written honestly per family -- a
// weak or thin edge-over-random result says so, never spun to sound stronger.
// entry_rule/exit_rule (CC-1 directive, "every strategy page must show entry/
// exit rules and trade frequency"): optional, hand-transcribed verbatim from
// the real nero_core/strategies/*.py source (exact numeric parameters --
// thresholds, multiples, periods) for families where this has been done so
// far. Absent for a family means "not yet added," never a fabricated blank --
// `mechanism` above (already prose, already real, just without exact numbers)
// stays the fallback for those.
export interface StrategyDescription {
  mechanism: string;
  verification_note: string;
  entry_rule?: string;
  exit_rule?: string;
}

export type StrategyDescriptions = Record<string, StrategyDescription>;

export interface StrategiesExport {
  schema_version: number;
  last_updated: string;
  strategies: StrategyRosterEntry[];
}

export interface OpenPosition {
  entry_price: number | null;
  entry_timestamp: string;
  candle_timestamp: string;
}

export interface StrategyStats {
  strategy: string;
  strategy_version: string;
  asset: string;
  resolved_trades: number;
  // Resolved round trips excluded by the export pipeline's quarantine filter
  // (quarantined incident window, mismatched entry/exit source, or unrecorded
  // source) -- optional because older cached exports predate this field.
  // resolved_trades==0 && unverified_trades==0 means "no signal yet"; > 0
  // means "trades happened but aren't confirmed clean" -- see lib/statLine.ts.
  unverified_trades?: number;
  win_rate: number | null;
  expectancy_r: number | null;
  avg_return_pct: number | null;
  signal_counts: Record<string, number>;
  open_position: OpenPosition | null;
  // Phase 1 Fix A (docs/investigations/phase_a_pead_ledger_anomaly.md): the
  // open-position counterpart to unverified_trades -- 1 when a trailing
  // ENTRY exists in the raw ledger but couldn't be confirmed as a clean open
  // position (unrecorded data_source), 0 otherwise. Optional because older
  // cached exports predate this field. See lib/statLine.ts.
  unverified_open_entries?: number;
}

export interface StatsExport {
  schema_version: number;
  last_updated: string;
  strategies: StrategyStats[];
}

export interface SiteSummary {
  configs_tested: number;
  strategies_survived: number;
  strategy_families_verified: number;
  tracking_since: string;
  last_curated: string;
}

export interface GraveyardEntry {
  name: string;
  family: string;
  what_was_tested: string;
  why_it_died: string;
  source_doc: string;
}

// Day 6/7 Strategy Doctor -- manually-curated, same convention as graveyard.json
// (see docs/site_data/README.md): one entry per killed FAMILY (not per individual
// graveyard row), synthesized from reading every family's source_doc(s), never
// auto-scraped.
export type FailurePattern =
  | "regime-filter-only"
  | "grid-shift-artifact"
  | "edge-over-random-negative"
  | "sample-too-thin"
  | "data-blocked"
  | "mechanism-doesn't-transfer";

export interface FailurePatternEntry {
  name: string;
  family: string;
  failure_pattern: FailurePattern;
  fixable: boolean;
  // Present only when fixable is true -- the mechanism-justified improvement
  // that addresses the diagnosed weakness, never a vague "try again" note.
  fix_rationale?: string;
  source_doc: string;
}

// Day 6/7 Repair Workbench -- up to 3 mechanism-justified hypotheses registered
// as candidates (not yet backtested; that is a separate future batch, per the
// task's own instruction).
export type RepairCandidateStatus = "candidate" | "testing" | "watchlist" | "promoted";

export interface RepairCandidate {
  parent_strategy: string;
  failure_pattern: FailurePattern;
  diagnosis: string;
  proposed_fix: string;
  hypothesis_name: string;
  status: RepairCandidateStatus;
}

// Day 7 ChatBot -- one static FAQ entry (Part A). Answers are pre-computed
// server-side from strategy_descriptions.json + stats.json, never fetched live.
export interface FaqEntry {
  question: string;
  answer: string;
}

// Day 7 ChatBot -- a single turn in the live-chat exchange (Part B). Sent to
// and returned from website/app/api/chat/route.ts; kept to the last 6 entries
// (3 exchanges) per the task's own conversation-history rule.
export interface ChatMessage {
  role: "user" | "assistant";
  content: string;
}

// Day 7 ChatBot -- resolved server-side (Server Component) from the same data
// every other panel on the strategy page already reads, then handed to the
// client ChatBot widget and forwarded to /api/chat so the system prompt can be
// built per-strategy. Never includes anything not already public on the page.
export interface StrategyChatContext {
  strategy_name: string;
  asset: string;
  timeframe: string;
  mechanism: string;
  verification_note: string;
  win_rate: number | null;
  current_signal: string;
}

// Written by nero_core/execution/heartbeat.py after every successful live
// scheduler run -- absence of this file (a fresh deploy, or the scheduler having
// never run) is a valid, non-error state, not something to fabricate a value for.
export interface HeartbeatStatus {
  last_successful_run: string;
  run_count_24h: number;
}

// Day 4/7 Quant Intelligence Panel, Part 1 -- one entry per candle FILE (i.e. per
// (asset, timeframe) pair, not per asset: GOLD and SILVER each have two files at
// two different timeframes with genuinely different metrics). Every metric is
// nullable independently -- insufficient history or an unrecognized timeframe
// nulls out just that field, never the whole entry, and never a fabricated
// number. There is deliberately no composite/overall score field here.
export interface QuantMetricsEntry {
  asset: string;
  timeframe: string;
  periods_per_year: number | null;
  window_used: number;
  rf_annual: number;
  rf_source: string;
  log_return_annualized: number | null;
  zscore_current: number | null;
  realized_vol_annualized: number | null;
  sharpe: number | null;
  sortino: number | null;
  computed_at: string;
}

export interface QuantMetricsExport {
  schema_version: number;
  last_updated: string;
  metrics: QuantMetricsEntry[];
}

// Day 5/7 Quant Intelligence Panel, Part 2 -- cross-asset relationships. No
// composite/overall score anywhere in this shape; each array is an independent
// descriptive statistic, per this panel's own research/education framing.
export interface CorrelationPair {
  asset_a: string;
  asset_b: string;
  timeframe: string;
  correlation: number | null;
  window_used: number;
  computed_at: string;
}

export interface VolatilityRegimeEntry {
  asset: string;
  timeframe: string;
  regime: "LOW" | "NORMAL" | "HIGH" | "EXTREME" | "NO_DATA";
  conditional_vol: number;
  vol_ratio: number;
  shock_score: number;
  model_used: string;
  computed_at: string;
}

export interface CointegrationEntry {
  asset_a: string;
  asset_b: string;
  timeframe_a: string;
  timeframe_b: string;
  pvalue: number | null;
  cointegrated: boolean | null;
  window_used: number;
  note: string;
  computed_at: string;
}

export interface LeadLagEntry {
  asset: string;
  benchmark: string;
  timeframe: string;
  best_lag: number | null;
  correlation: number | null;
  window_used: number;
  note: string;
  computed_at: string;
}

export interface QuantCrossAssetExport {
  schema_version: number;
  last_updated: string;
  correlation_matrix: CorrelationPair[];
  volatility_regimes: VolatilityRegimeEntry[];
  cointegration: CointegrationEntry[];
  lead_lag: LeadLagEntry[];
}

// Research Agent (feature/research-agent) -- docs/site_data/agent_hypotheses.json.
// Append-only: one entry per hypothesis ever generated, written by
// nero_core.research_agent.hypothesis_gen. `structured_entry_rule` /
// `structured_exit_plan` are null whenever the LLM said the free-text
// entry_rule/exit_rule/stop_rule genuinely can't be expressed in the
// machine-checkable DSL -- never a forced approximation, so this stays
// optional/untyped here rather than a fully-typed shape.
export interface AgentHypothesis {
  scan_finding: string;
  scan_finding_type: string;
  hypothesis_name: string;
  mechanism: string;
  entry_rule: string;
  structured_entry_rule: Record<string, unknown> | null;
  exit_rule: string;
  stop_rule: string;
  structured_exit_plan: Record<string, unknown> | null;
  asset: string;
  timeframe: string;
  differs_from_graveyard: string;
  expected_frequency_claim: number | null;
  generated_at: string;
  cost_usd: number;
  source: string;
}

// docs/site_data/agent_test_results.json -- one entry per hypothesis tested
// (or gate-rejected before ever reaching the harness), written by
// nero_core.research_agent.auto_tester. SKIPPED covers both TOO_SLOW and
// UNMEASURABLE gate rejections -- train/test are null for those, since no
// backtest ever ran.
export type AgentTestVerdict = "SURVIVED" | "PROMISING-WATCHLIST" | "DIED" | "UNTESTABLE" | "SKIPPED";
export type AgentFrequencyClassification = "FAST" | "VIABLE" | "TOO_SLOW" | "UNMEASURABLE";

export interface AgentBootstrapCI {
  sample_size: number;
  mean_r: number;
  lower_2_5: number;
  upper_97_5: number;
  crosses_zero: boolean;
}

export interface AgentRandomBaseline {
  real_expectancy_r: number;
  mean_random_expectancy_r: number;
  p95_random_expectancy_r: number;
  edge_over_random: number;
  target_trade_count: number;
  realized_mean_trade_count: number;
  n_runs: number;
  caveat: string | null;
}

export interface AgentHalfStats {
  trades: number;
  expectancy_r: number;
  bootstrap_ci: AgentBootstrapCI | null;
  random_baseline: AgentRandomBaseline | null;
}

export interface AgentTestResult {
  hypothesis_name: string;
  asset: string;
  timeframe: string;
  verdict: AgentTestVerdict;
  review_status: string;
  frequency_classification: AgentFrequencyClassification;
  measured_trades_per_year: number | null;
  expected_time_to_30_trades_months: number | null;
  reason: string;
  train: AgentHalfStats | null;
  test: AgentHalfStats | null;
  tested_at: string;
}

// docs/site_data/agent_performance.json -- written by
// nero_core.research_agent.performance after every ENABLED pipeline run.
// survival_rate is null (never a fabricated 0.0) until at least one
// hypothesis has ever been tested, and its denominator excludes SKIPPED
// (gate-rejected) hypotheses on purpose -- they were never given a chance to
// survive or die.
export interface AgentPerformanceCumulative {
  hypotheses_generated: number;
  duplicates_skipped: number;
  too_slow_rejected: number;
  unmeasurable_rejected: number;
  tested: number;
  survived: number;
  promising_watchlist: number;
  died: number;
  untestable: number;
  no_candles_available: number;
  llm_calls_made: number;
  total_llm_cost_usd: number;
  survival_rate: number | null;
  // CC-1 Factory Loop closeout, item 3: a call that timed out (ReadTimeout)
  // is recorded as UNKNOWN cost, never a fabricated $0 -- see
  // nero_core.research_agent.hypothesis_gen's own RejectedBeforeTokenProcessingError
  // vs "cost UNKNOWN, not confirmed $0" distinction. Optional: absent on the
  // two pre-instrumentation 2026-07-29 runs, which predate this field
  // existing at all -- absence must read as "not tracked yet," never as "0."
  calls_with_unknown_cost?: number;
  web_calls_with_unknown_cost?: number;
}

// STATUS_DISABLED / STATUS_ERROR / STATUS_CLEAN in
// nero_core.research_agent.pipeline -- "error" means at least one entry in
// `errors` below (scan or hypothesis-generation failure); it does NOT mean
// the whole run aborted -- a run can be status="error" and still have
// nonzero hypotheses_generated/llm_calls_made if only some sources failed.
export type AgentRunStatus = "disabled" | "error" | "clean";

export interface AgentPerformanceRunError {
  phase: string;
  context: string;
  message: string;
}

export interface AgentPerformanceRun {
  run_at: string;
  enabled: boolean;
  reason: string;
  status: AgentRunStatus;
  errors: AgentPerformanceRunError[];
  hypotheses_generated: number;
  duplicates_skipped: number;
  too_slow_rejected: number;
  unmeasurable_rejected: number;
  tested: number;
  survived: number;
  promising_watchlist: number;
  died: number;
  untestable: number;
  no_candles_available: number;
  llm_calls_made: number;
  total_llm_cost_usd: number;
  cost_limit_hit: boolean;
  calls_with_unknown_cost?: number;
}

// docs/site_data/agent_run_summaries.json -- written by
// tools/research_agent_run_summary.py (CC-1 review item 2), committed on
// every research_agent_manual.yml run (unlike agent_hypotheses.json/
// agent_test_results.json, which stay artifact-only/uncommitted -- see that
// workflow's own comments). Carries only AGGREGATE, DERIVED statistics --
// counts, ratios, which hypothesis NAMES were TOO_SLOW -- never raw
// hypothesis mechanism/entry-rule text, so committing it does not carry the
// "un-reviewed bad proposal, can't be undone" risk that rule exists to guard
// against.
//
// DELIBERATELY MINIMAL: the real committed file also carries run_aggregate
// (by_channel breakdown), per_hypothesis, calibration, and a
// backfilled/data_completeness shape for one 2026-08-03 entry whose
// per-hypothesis names were never captured (see that entry's own
// provenance_note) -- only the fields this site actually reads (too_slow
// names, CC-1 Factory Loop closeout item 4a) are modeled here; TypeScript's
// structural typing does not require every real JSON field to be declared.
export interface AgentRunSummaryTooSlowEntry {
  hypothesis_name: string;
  measured_trades_per_year: number;
  llm_claimed_trades_per_year: number;
}

export interface AgentRunSummary {
  run_at: string;
  // null (never []) on the one backfilled 2026-08-03 entry, whose
  // per-hypothesis names are honestly unavailable (data_completeness:
  // "aggregate_only") -- must not be treated as "zero TOO_SLOW that run."
  too_slow: AgentRunSummaryTooSlowEntry[] | null;
}

// A correction record NEVER edits the run entry it applies to (see
// docs/site_data/agent_performance.json's own two 2026-07-29 entries, which
// predate `status`/`errors` existing at all) -- it is an appended,
// independently-dated annotation inferring what that field would have said,
// with its evidentiary basis stated explicitly. Optional: only present once
// at least one correction has ever been recorded.
export interface AgentPerformanceCorrection {
  correction_id: string;
  applies_to_run_at: string;
  corrected_at: string;
  reason_field_absent: string;
  inferred_status: AgentRunStatus;
  inferred_status_basis: string;
  note: string;
}

export interface AgentPerformanceExport {
  schema_version: number;
  last_updated: string | null;
  cumulative: AgentPerformanceCumulative;
  runs: AgentPerformanceRun[];
  corrections?: AgentPerformanceCorrection[];
}

// CC-1 Factory Loop directive, item 9 -- docs/site_data/factory_loop_status.json,
// written by tools/factory_loop_status_summary.py, following
// tools/research_agent_run_summary.py's exact "compute -> print -> commit"
// convention. `forward_trial` (NOT "trial") per item 8c's locked naming
// decision -- the site's EXISTING public "Under Trial" roster tier
// (see lib/tier.ts, 17 live configs as of 2026-08) is a completely different,
// unrelated concept from this new one; the new concept is called
// "Forward Trial" everywhere on this site so the two are never confused
// under the same word.
export interface FactoryLoopForwardTrialStatus {
  count: number;
  by_origin: { adam: number; eve: number; repaired: number };
  // item 4b/9b: how many OPEN entries project beyond the 2-year visibility
  // horizon (nero_core.research_agent.trial.UNMEASURABLE_HORIZON_YEARS) --
  // surfaced explicitly so a healthy-looking count is never silently mostly
  // unmeasurable entries.
  unmeasurable_count: number;
}

export interface FactoryLoopGraveyardStatus {
  count: number;
  distilled_this_period: number;
  pending_review: number;
}

export interface FactoryLoopRepairStatus {
  count: number;
  open_chains: number;
  resolved_chains: number;
}

export interface FactoryLoopStatusExport {
  schema_version: number;
  last_updated: string;
  forward_trial: FactoryLoopForwardTrialStatus;
  graveyard: FactoryLoopGraveyardStatus;
  repair: FactoryLoopRepairStatus;
}

// CC-1 directive, item 1c/5f: the per-record file (nero_core.research_agent.
// trial.TrialRecord.to_dict(), appended by tools/factory_loop_run.py) --
// distinct from FactoryLoopStatusExport above, which is only the aggregate
// counts. Deliberately omits forward_tracking_db_ref (a local filesystem
// path on whichever machine ran the admission, not meaningful to a site
// reader). Already fetchable with zero export step (docs/site_data/
// forward_trial.json, same "lives under docs/site_data/ already" convention
// as Eve's three files below).
export interface ForwardTrialSourceRef {
  origin: "fresh" | "repaired";
  origin_agent: "adam" | "eve";
  hypothesis_name: string;
  session_id_or_run_ref: string | null;
  repair_chain_id?: string;
  attempt_id?: string;
}

// CC-1 Part D6/D6a: nero_core/execution/export_trial_entries.py's own output
// shape. A genuine Forward Trial ENTRY (an execution_log row with strategy
// TRIAL:<trial_id> and signal_type ENTRY) -- distinct from ForwardTrialRecord
// above, which reflects Trial ADMISSION status, not a live market position.
export interface TrialEntry {
  execution_log_id: number;
  trial_id: string;
  hypothesis_name: string | null;
  origin_agent: "adam" | "eve" | null;
  asset: string;
  timeframe: string | null;
  direction: "LONG" | "SHORT" | null;
  entry_price: number | null;
  stop_loss: number | null;
  target: number | null;
  timestamp: string;
  candle_timestamp: number;
}

// CC-1 Part E: nero_core/execution/bellwether_overlay.py::export_macro_reads_json's
// own output shape -- one row per (run_id, asset) Bellwether run, plus every
// ORDERFLOW_IMBALANCE/BTC ENTRY ever evaluated for a macro conflict.
export type DataProvenanceLabel = "real" | "synthetic" | "mixed" | "unavailable";

export interface MacroReadRecord {
  run_id: string;
  timestamp: string;
  asset: "GOLD" | "BITCOIN";
  bias: string;
  confidence: number;
  agreement: number;
  coverage: number;
  probability_up: number;
  provenance_breakdown: Record<string, DataProvenanceLabel>;
  reasoning: string;
  risks: string[];
  alternative_scenarios: Array<{
    name: string;
    probability: number;
    gold_bias: string;
    btc_bias: string;
    narrative: string;
  }>;
  data_mode: string;
}

export interface MacroConflictFlagRecord {
  execution_log_id: number;
  macro_read_id: number | null;
  strategy: string;
  asset: string;
  entry_direction: string | null;
  conflicted: boolean;
  status: "evaluated" | "insufficient_data" | "circuit_breaker_open";
  reason: string;
  evaluated_at: string;
}

export interface MacroReadsExport {
  schema_version: number;
  last_updated: string;
  macro_reads: MacroReadRecord[];
  conflict_flags: MacroConflictFlagRecord[];
}

export interface TrialEntriesExport {
  schema_version: number;
  last_updated: string;
  entries: TrialEntry[];
}

// CC-1 overnight directive, Part 4: nero_core/execution/export_news_sentiment.py's
// own output shape -- every real news_sentiment_log row, all time, both real
// NEWS_SENTIMENT configs (v1.0.0 keyword-based, v2.0.0-llm-claude).
export interface NewsSentimentEntry {
  id: number;
  run_id: string;
  asset: string;
  strategy_version: string;
  news_timestamp: string | null;
  fetch_timestamp: string;
  sentiment_score: number | null;
  signal_type: "BUY_BIAS" | "SELL_BIAS" | "NEUTRAL";
  confidence: number;
  reasoning: string;
  source: string;
}

export interface NewsSentimentExport {
  schema_version: number;
  last_updated: string;
  entries: NewsSentimentEntry[];
}

export interface ForwardTrialRecord {
  trial_id: string;
  source_hypothesis_ref: ForwardTrialSourceRef;
  entry_verdict: { verdict: string | null; [key: string]: unknown };
  measured_trades_per_year: number | null;
  projected_time_to_min_sample_years: number | null;
  projected_time_to_min_sample_label: string;
  opened_at: string;
  status: "OPEN" | "SURVIVED_TRIAL" | "FAILED_TRIAL";
  attribution: string;
}

// --- Eve (nero_core/eve/) -- CC-1 Master Directive Phase 2. All three files
// below already live under docs/site_data/ (confirmed directly against
// nero_core/eve/storage.py's own DEFAULT_HYPOTHESES_PATH/
// DEFAULT_BUDGET_LEDGER_PATH/EVE_SESSIONS_DIR), so fetchJson reaches them
// with no export step -- unlike eve_sessions/<id>.json (also under
// docs/site_data/, but one file PER session, not a single list), which this
// phase deliberately does not fetch: eve_session_registry.json's own
// classification/reason text already carries everything Phase 2's Session
// Health panel needs (see this branch's own closing report for the full
// plumbing finding). Deliberately minimal -- only the fields this site
// reads, not every real field these files carry.

export interface EveRawHypothesis {
  hypothesis_name?: string;
  mechanism?: string;
  asset?: string;
  timeframe?: string;
  // CC-1 directive, "every strategy page must show entry/exit rules and
  // trade frequency": the real DSL rule fields, already present on every
  // committed eve_hypotheses.json record, just not read by this site until
  // now -- see lib/ruleTranslation.ts.
  structured_entry_rule?: Record<string, unknown> | null;
  structured_exit_plan?: Record<string, unknown> | null;
  // CC-1 overnight directive, Part 1.3 (Learning Curve, Near-miss funnel):
  // real, already-validated declared-refinement field -- see B1's own work
  // (nero_core/eve/scoring.py::validate_derived_from).
  derived_from?: { parent_hypothesis_name?: string } | null;
}

export interface EveHypothesisRecord {
  session_id: string;
  raw_hypothesis: EveRawHypothesis;
  testability: string;
  verdict_combined: string | null;
  frequency_classification: string | null;
  measured_trades_per_year: number | null;
  contamination_tags: Array<{ tag: string }>;
  // CC-1 overnight directive, Part 1.3 (Learning Curve, Near-miss funnel):
  // real fields already on every committed record, just not read by this
  // site until now -- see nero_core/eve/context.py's own _is_near_miss logic
  // (reproduced client-side in lib/learningCurve.ts).
  verdict_is?: string | null;
  verdict_oos?: string | null;
  fdr_survives_is?: boolean | null;
  fdr_survives_oos?: boolean | null;
}

export interface EveSessionRegistryEntry {
  session_id: string;
  counts_toward_pre_registered_8: boolean;
  classification: string;
  reason: string;
  session_label?: string;
}

export interface EveSessionRegistryPreRegistration {
  sessions_budgeted: string;
  eve_must_clear: string;
  kill_criterion: string;
}

export interface EveSessionRegistryExport {
  pre_registration: EveSessionRegistryPreRegistration;
  sessions: EveSessionRegistryEntry[];
  next_countable_session_number: number;
}

// CC-1 overnight directive, Part 1.1 (Learning Curve): the real, auto-written
// per-session record under docs/site_data/eve_sessions/<id>.json. Deliberately
// minimal -- only the two fields the Reliability chart needs, matching this
// file's own "only the fields this site reads" discipline. `terminated_because`
// is always a real string on a written file ("end_session_called" on a clean
// completion, "crashed_mid_session" on a crash the crash-safety mechanism
// caught); `partial` is `true` only on a crash-caught record.
export interface EveSessionRecord {
  session_id: string;
  terminated_because: string;
  partial?: boolean;
}

export interface EveBudgetLedgerEntry {
  session_id: string;
  status: "reserved" | "actual" | "released";
  actual_cost_usd: number | null;
  projected_cost_usd: number;
  month: string;
  crash_reason?: string;
  crash_marked_at?: string;
}

// CC-1 directive Part B3a: one real, live-computed condition on a survivor
// strategy's own entry rule -- see nero_core/execution/export_survivor_distance.py's
// own docstring for why this is deliberately per-condition, never a combined score.
export interface SurvivorDistanceCondition {
  label: string;
  unit: "pct" | "rsi_points" | "z_units" | "boolean_state";
  distance: number | null;
  note?: string;
  raw_zscore?: number;
}

export interface SurvivorDistanceEntry {
  strategy_id: string;
  asset: string;
  timeframe: string;
  candle_close_time_ms: number;
  conditions: SurvivorDistanceCondition[];
  computed_at: string;
}

export interface SurvivorDistanceExport {
  schema_version: number;
  last_updated: string;
  distances: SurvivorDistanceEntry[];
  errors: { strategy: string; message: string }[];
}
