"""CLI: feature/external-candidates-formal-test -- formal, no-special-trust
test of 5 EXTERNALLY-SOURCED strategy candidates through Vatican's own
harness, on Vatican's own data pipeline.

PROVENANCE: these 5 hypotheses were sourced from an external system, NOT
generated by Vatican's own scanner/LLM/web-search discovery channels. Per
this project's standing rule (see nero_core.research_agent.hypothesis_gen's
own "RULE 2"/"no special treatment" tests), no external source gets special
trust -- an externally-reported win rate, profit factor, expectancy, or even
the source's own out-of-sample verdict is NEVER treated as pre-confirmed
here. The harness decides, on Vatican's own data, from scratch, exactly like
any other submission.

NAMING COLLISION -- READ BEFORE TOUCHING ANY NAME BELOW: this repo already
has NATIVE WISE_MAN_HOLD_V1-V10 and ADX_RANGE_V1-V4 hypotheses (see
tests/test_research_agent_philosophy_hypotheses_variants.py,
docs/philosophy_hypotheses_live_test_results.json). Two of the 5 external
candidates below share bare names with native ones (ADX_RANGE_V3,
ADX_RANGE_V4) but describe a COMPLETELY DIFFERENT rule (bidirectional BB
entry + dynamic SMA20 target + 2xATR stop, vs. the native version's
long-only ADX-threshold-only entry + a deliberately unreachable PROXY
target -- see ADX_RANGE_VARIANTS's own proxy_test_of field). Every candidate
here is renamed with an EXT_ prefix (see EXTERNAL_CANDIDATES below) SPECIFICALLY
to make that collision structurally impossible in any shared log/report --
see tests/test_external_candidates_formal_test.py::NoCollisionWithNativeGraveyardTest
for the proof this holds even under a naive dict-merge with the native results file.
The WISE_MAN_HOLD_V5/V6 percentage targets happen to numerically match this
repo's own native V5/V6 definitions exactly (same rule, newly applied to
ETH/EUR-USD instead of BTC) -- renamed anyway, since these are independently
re-verified on Vatican's own pipeline, never assumed identical in outcome to
either the native BTC run or the external source's own report.

TASK 1 FINDING -- 2 of 5 are UNTESTABLE, not run: EXT_ADX_RANGE_V3_BTC_1D and
EXT_ADX_RANGE_V4_BTC_1D specify a BIDIRECTIONAL (long AND short) rule with a
direction-aware stop and a dynamic SMA20 target on either side. Verified
directly (not assumed) that nero_core.research_agent.auto_tester has ZERO
short-side capability anywhere in its entry/exit machinery --
_size_entry_for_hypothesis unconditionally calls
`apply_slippage(raw_entry, params.slippage_bps, "buy")` and prices its stop
BELOW / target ABOVE entry; _evaluate_exit_for_hypothesis checks
`low <= trade.stop_loss` (never `high >=`) and treats a dynamic target
crossing the SAME direction as this codebase's own established long-only
convention throughout. There is no `direction` field anywhere in
StructuredRule/Condition/ExitPlan. The only bidirectional backtest machinery
anywhere in this codebase (RANGE_MEAN_REVERSION's own `allow_short` flag,
FVG_REVERSION's own long+short logic) is bespoke to THAT strategy's own
specific entry/exit mechanism, not a generic rule_dsl-configurable one -- so
routing these 2 hypotheses through either would not be "reusing the harness
for this rule," it would be a different rule running under this rule's name.
Building genuinely new short-side entry/exit machinery into rule_dsl/
auto_tester would be a real, foundational engine extension (new P&L sign
conventions, new stop/target check directions, real risk of a subtle
direction-inversion bug) -- exactly the kind of thing this task's own
instruction says to REUSE, not reimplement, and exactly the kind of thing
this project's own established discipline says to flag rather than guess at
under task-scope time pressure (same standard as the recent commodity_futures
None decision -- verify a real capability before claiming it, don't build one
hastily to force a result). Flagged UNTESTABLE, not run, not approximated
(e.g. NOT silently tested long-side-only, which would misrepresent the rule).

TASK 2 -- DATA SOURCING: full available history for each asset, Vatican's own
pipeline, fetched fresh (not the external source's own date-limited window).
EXT_WISE_MAN_HOLD_V5_ETH_4H uses Binance ETHUSDT direct 4h candles -- same
provider/instrument the external source itself used. EXT_WISE_MAN_HOLD_V6/V5_
EURUSD_4H use Vatican's own EUR/USD 4h candles (Twelve Data native, via
tools.philosophy_hypotheses_live_test.fetch_full_history's own forex dispatch)
-- EXPLICITLY NOT the external source's yfinance-1h-resampled-to-4h
construction. This is a genuinely different candle-construction method
(native provider-supplied 4h bars vs. hourly bars aggregated into 4h bins by
a different vendor) -- a difference in trade count/timing/even which exact
4h boundary each candle closes on, relative to the external report, is
EXPECTED from this alone, not a sign either pipeline is broken.

TASK 3 -- runs frequency_gate -> auto_tester via tools.philosophy_hypotheses_
live_test.run_hypothesis_live, reused directly (see
tests/test_external_candidates_formal_test.py::HarnessReuseTest's assertIs
proofs) -- exactly the same call shape the native philosophy-hypotheses batch
used. No pre-seeding from the external source's own reported verdict for any
candidate, including EXT_WISE_MAN_HOLD_V5_ETH_4H, which the external source
itself already reports as DIED in their own OOS check -- still run fresh here
for a genuinely independent result.

ANTI-P-HACKING: EXTERNAL_CANDIDATES below is the full, fixed, pre-registered
set for this task -- 5 entries, unconditionally, run in this exact order,
never added to or pruned based on an interim result.

CRITICAL SAFETY: writes only to the report path this module's own main()
resolves -- never to docs/site_data/agent_test_results.json (the shared
production ledger) or to docs/philosophy_hypotheses_live_test_results.json
(the native graveyard file -- see the collision test referenced above).
Imports nothing from nero_core.execution.live_scheduler or
nero_core.strategies.registry.

Usage:
    python -m tools.external_candidates_formal_test
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from nero_core.data_sources.market_data import MarketDataClient
from nero_core.research_agent import auto_tester
from nero_core.strategies.mean_reversion import MeanReversionParameters
from tools.philosophy_hypotheses_live_test import _to_jsonable, fetch_full_history, run_hypothesis_live

REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REPORT_PATH = REPO_ROOT / "docs" / "external_candidates_formal_test_results.json"

# Common engine rules, per the external source's own spec, applied to all 5.
CRYPTO_FEE_BPS = 10.0  # matches MeanReversionParameters' own crypto-sized default exactly
FOREX_FEE_BPS = 2.0    # OVERRIDE -- MeanReversionParameters' default (10.0) is crypto-sized
SLIPPAGE_BPS = 2.0     # matches the default exactly, for every asset
INITIAL_EQUITY = 10_000.0
RISK_PER_TRADE = 0.01  # 1% -- matches the default exactly

CRYPTO_PARAMS = MeanReversionParameters(
    initial_equity=INITIAL_EQUITY, risk_per_trade=RISK_PER_TRADE, fee_bps=CRYPTO_FEE_BPS, slippage_bps=SLIPPAGE_BPS,
)
FOREX_PARAMS = MeanReversionParameters(
    initial_equity=INITIAL_EQUITY, risk_per_trade=RISK_PER_TRADE, fee_bps=FOREX_FEE_BPS, slippage_bps=SLIPPAGE_BPS,
)

# Shared entry rule for all 3 WISE_MAN_HOLD-family candidates: long only,
# ADX14 < 25 AND close < BB lower AND ATR14 > 0 ("no open trade" is enforced
# structurally by auto_tester.run_backtest's own one-position-at-a-time
# convention, never an explicit condition -- matches the native WISE_MAN_HOLD
# family's own established pattern).
WISE_MAN_EXT_ENTRY_RULE = {
    "conditions": [
        {"field": "close", "op": "lt", "compare_to_field": "bb_lower"},
        {"field": "adx14", "op": "lt", "value": 25.0},
        {"field": "atr14", "op": "gt", "value": 0.0},
    ],
}

# Shared exit shape for all 3: percentage stop/target + a 2-consecutive-bar
# ADX regime-break, no time cap. Exit precedence (stop, then target, then
# regime-break, then time) is auto_tester._evaluate_exit_for_hypothesis's own
# existing, unchanged precedence -- matches the external spec exactly with
# zero engine changes needed (already proven: this combination parses and
# was smoke-tested directly before writing this file).
def _wise_man_ext_exit_plan(stop_pct: float, target_pct: float) -> dict:
    return {
        "stop_pct_of_entry": stop_pct,
        "target_pct_of_entry": target_pct,
        "regime_break_condition": {"field": "adx14", "op": "gte", "value": 28.0},
        "regime_break_consecutive_bars": 2,
    }


UNTESTABLE_BIDIRECTIONAL_REASON = (
    "Rule requires a BIDIRECTIONAL (long AND short) entry/exit with a direction-aware "
    "stop and a dynamic SMA20 target on either side. Verified directly: "
    "nero_core.research_agent.auto_tester's entry/exit machinery is unconditionally "
    "long-only throughout (_size_entry_for_hypothesis always enters via apply_slippage(..., "
    "\"buy\"), prices stop below / target above entry; _evaluate_exit_for_hypothesis checks "
    "low <= stop_loss, never high >=) -- no direction field exists anywhere in StructuredRule/"
    "Condition/ExitPlan. The only bidirectional backtest machinery in this codebase "
    "(RANGE_MEAN_REVERSION's allow_short, FVG_REVERSION's own logic) is bespoke to that "
    "strategy's own specific mechanism, not a generic DSL -- reusing either would not be "
    "testing this rule. Building new short-side engine machinery would be a real, "
    "foundational extension outside this task's reuse-the-harness instruction, with real risk "
    "of a subtle direction-inversion bug if done under this task's scope. Flagged UNTESTABLE, "
    "not approximated (e.g. NOT silently tested long-side-only, which would misrepresent the rule)."
)

# The full, fixed, pre-registered set -- 5 entries, in this exact order.
# (name, asset, timeframe, params_or_None_if_untestable, entry_rule_or_None, exit_plan_or_None, untestable_reason_or_None)
EXTERNAL_CANDIDATES = [
    {
        "name": "EXT_WISE_MAN_HOLD_V5_ETH_4H",
        "asset": "ETH", "timeframe": "4h",
        "backtest_params": CRYPTO_PARAMS,
        "structured_entry_rule": WISE_MAN_EXT_ENTRY_RULE,
        "structured_exit_plan": _wise_man_ext_exit_plan(stop_pct=0.015, target_pct=0.03),
        "untestable_reason": None,
        "external_source_note": (
            "External source itself already reports this candidate as DIED in their own OOS "
            "check. Still run fresh here on Vatican's own data/pipeline for a genuinely "
            "independent result -- their verdict is not pre-seeded or assumed."
        ),
    },
    {
        "name": "EXT_WISE_MAN_HOLD_V6_EURUSD_4H",
        "asset": "EUR/USD", "timeframe": "4h",
        "backtest_params": FOREX_PARAMS,
        "structured_entry_rule": WISE_MAN_EXT_ENTRY_RULE,
        "structured_exit_plan": _wise_man_ext_exit_plan(stop_pct=0.01, target_pct=0.01),
        "untestable_reason": None,
        "external_source_note": None,
    },
    {
        "name": "EXT_WISE_MAN_HOLD_V5_EURUSD_4H",
        "asset": "EUR/USD", "timeframe": "4h",
        "backtest_params": FOREX_PARAMS,
        "structured_entry_rule": WISE_MAN_EXT_ENTRY_RULE,
        "structured_exit_plan": _wise_man_ext_exit_plan(stop_pct=0.015, target_pct=0.03),
        "untestable_reason": None,
        "external_source_note": None,
    },
    {
        "name": "EXT_ADX_RANGE_V3_BTC_1D",
        "asset": "BTC", "timeframe": "1d",
        "backtest_params": None,
        "structured_entry_rule": None,
        "structured_exit_plan": None,
        "untestable_reason": UNTESTABLE_BIDIRECTIONAL_REASON,
        "external_source_note": None,
    },
    {
        "name": "EXT_ADX_RANGE_V4_BTC_1D",
        "asset": "BTC", "timeframe": "1d",
        "backtest_params": None,
        "structured_entry_rule": None,
        "structured_exit_plan": None,
        "untestable_reason": UNTESTABLE_BIDIRECTIONAL_REASON,
        "external_source_note": None,
    },
]

NATIVE_NAME_COLLISIONS_TO_AVOID = frozenset({
    "WISE_MAN_HOLD_V1", "WISE_MAN_HOLD_V2", "WISE_MAN_HOLD_V3", "WISE_MAN_HOLD_V4",
    "WISE_MAN_HOLD_V5", "WISE_MAN_HOLD_V6", "WISE_MAN_HOLD_V7", "WISE_MAN_HOLD_V8",
    "WISE_MAN_HOLD_V9", "WISE_MAN_HOLD_V10", "WISE_MAN_ASYMMETRIC_HOLD",
    "ADX_RANGE_V1", "ADX_RANGE_V2", "ADX_RANGE_V3", "ADX_RANGE_V4",
})


def main(report_path: Path = DEFAULT_REPORT_PATH) -> dict:
    client = MarketDataClient()
    now = datetime.now(timezone.utc)
    history_cache: dict[tuple[str, str], pd.DataFrame] = {}
    runs: dict[str, dict] = {}

    print(f"=== external_candidates_formal_test: {len(EXTERNAL_CANDIDATES)} pre-registered candidates, now={now.isoformat()} ===", flush=True)

    def _write_report() -> dict:
        report = {"generated_at": now.isoformat(), "runs": runs}
        report_path.parent.mkdir(parents=True, exist_ok=True)
        report_path.write_text(json.dumps(report, indent=2, default=str))
        return report

    for idx, candidate in enumerate(EXTERNAL_CANDIDATES, start=1):
        name = candidate["name"]
        assert name not in NATIVE_NAME_COLLISIONS_TO_AVOID, f"{name} collides with a native graveyard name"

        if candidate["untestable_reason"] is not None:
            print(f"[{idx}/{len(EXTERNAL_CANDIDATES)}] {name}: UNTESTABLE -- {candidate['untestable_reason'][:100]}...", flush=True)
            runs[name] = {"name": name, "verdict": auto_tester.VERDICT_UNTESTABLE, "reason": candidate["untestable_reason"]}
            _write_report()
            continue

        asset, timeframe = candidate["asset"], candidate["timeframe"]
        key = (asset, timeframe)
        if key not in history_cache:
            print(f"[{idx}/{len(EXTERNAL_CANDIDATES)}] fetching full history for {asset}/{timeframe} ...", flush=True)
            history_cache[key] = fetch_full_history(asset, timeframe, client)
            print(f"  -> {len(history_cache[key])} candles", flush=True)
        candles = history_cache[key]

        hypothesis = {
            "hypothesis_name": name, "asset": asset, "timeframe": timeframe,
            "generated_at": now.isoformat(),
            "structured_entry_rule": candidate["structured_entry_rule"],
            "structured_exit_plan": candidate["structured_exit_plan"],
        }
        print(f"[{idx}/{len(EXTERNAL_CANDIDATES)}] {name}: running frequency_gate + harness ...", flush=True)
        run = run_hypothesis_live(hypothesis, candles, now, client=client, backtest_params=candidate["backtest_params"])
        result = run["result"]
        grid_note = f" grid_shift={len(run['grid_shift'])} offsets" if run["grid_shift"] else ""
        print(
            f"[{idx}/{len(EXTERNAL_CANDIDATES)}] {name} done: freq={result.frequency_classification} "
            f"verdict={result.verdict}{grid_note} -- {result.reason}",
            flush=True,
        )
        runs[name] = {"name": name, "asset": asset, "timeframe": timeframe, **_to_jsonable(run)}
        _write_report()
        print(f"  -> report updated at {report_path} ({len(runs)}/{len(EXTERNAL_CANDIDATES)} runs so far)", flush=True)

    report = _write_report()
    print(f"\n=== DONE. report written to {report_path} ===", flush=True)
    return report


if __name__ == "__main__":
    main()
